spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/analyzer}
    username: ${SPRING_DATASOURCE_USERNAME:analyzer}
    password: ${SPRING_DATASOURCE_PASSWORD:analyzer}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
