CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE analysis_profile_technologies
(
    profile_id UUID        NOT NULL,
    technology VARCHAR(80) NOT NULL,
    position   INTEGER     NOT NULL,
    CONSTRAINT pk_analysis_profile_technologies PRIMARY KEY (profile_id, position)
);

CREATE TABLE analysis_profiles
(
    id                     UUID                           NOT NULL,
    owner_id               UUID                           NOT NULL,
    version                BIGINT,
    name                   VARCHAR(120)                   NOT NULL,
    direction              VARCHAR(32)                    NOT NULL,
    specialization         VARCHAR(80)                    NOT NULL,
    target_grade           VARCHAR(32)                    NOT NULL,
    preset                 VARCHAR(32),
    market_filters         JSONB                          NOT NULL,
    scoring_policy_version VARCHAR(64)                    NOT NULL,
    created_at             TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at             TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    deleted_at             TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_analysis_profiles PRIMARY KEY (id)
);

CREATE TABLE analysis_runs
(
    id                 UUID                           NOT NULL,
    version            BIGINT,
    owner_id           UUID                           NOT NULL,
    profile_id         UUID                           NOT NULL,
    profile_version    BIGINT                         NOT NULL,
    input_sha256       VARCHAR(64)                    NOT NULL,
    status             VARCHAR(32)                    NOT NULL,
    target_grade       VARCHAR(32)                    NOT NULL,
    detected_grade     VARCHAR(32),
    created_at         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    completed_at       TIMESTAMP(6) WITHOUT TIME ZONE,
    failure_code       VARCHAR(64),
    market_snapshot_id UUID,
    profile_snapshot   JSONB                          NOT NULL,
    effective_config   JSONB,
    result             JSONB,
    llm_response       JSONB,
    extracted_text     TEXT,
    system_instruction TEXT,
    prompt_input       TEXT,
    response_schema    TEXT,
    CONSTRAINT pk_analysis_runs PRIMARY KEY (id)
);

CREATE TABLE market_snapshot_criteria
(
    snapshot_id     UUID         NOT NULL,
    label           VARCHAR(500) NOT NULL,
    description     TEXT         NOT NULL,
    requirement_ids JSONB        NOT NULL,
    position        INTEGER      NOT NULL,
    CONSTRAINT pk_market_snapshot_criteria PRIMARY KEY (snapshot_id, position)
);

CREATE TABLE market_snapshot_requirements
(
    snapshot_id         UUID             NOT NULL,
    requirement_id      VARCHAR(256)     NOT NULL,
    label               VARCHAR(500)     NOT NULL,
    type                VARCHAR(32)      NOT NULL,
    total_vacancy_count INTEGER          NOT NULL,
    required_count      INTEGER          NOT NULL,
    preferred_count     INTEGER          NOT NULL,
    optional_count      INTEGER          NOT NULL,
    frequency           DOUBLE PRECISION NOT NULL,
    required_frequency  DOUBLE PRECISION NOT NULL,
    preferred_frequency DOUBLE PRECISION NOT NULL,
    optional_frequency  DOUBLE PRECISION NOT NULL,
    position            INTEGER          NOT NULL,
    CONSTRAINT pk_market_snapshot_requirements PRIMARY KEY (snapshot_id, position)
);

CREATE TABLE market_snapshots
(
    id                   UUID                           NOT NULL,
    provenance           JSONB                          NOT NULL,
    generated_at         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    pipeline_version     VARCHAR(64)                    NOT NULL,
    segment              JSONB                          NOT NULL,
    queries              JSONB                          NOT NULL,
    vacancies            JSONB                          NOT NULL,
    vacancy_requirements JSONB                          NOT NULL,
    warnings             JSONB                          NOT NULL,
    scanned_count        INTEGER                        NOT NULL,
    unique_count         INTEGER                        NOT NULL,
    truncated            BOOLEAN                        NOT NULL,
    fetched_count        INTEGER                        NOT NULL,
    processed_count      INTEGER                        NOT NULL,
    failed_count         INTEGER                        NOT NULL,
    sufficient_sample    BOOLEAN                        NOT NULL,
    CONSTRAINT pk_market_snapshots PRIMARY KEY (id)
);

CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE vacancies
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id       VARCHAR(128)                            NOT NULL,
    source            VARCHAR(64)                             NOT NULL,
    title             VARCHAR(500)                            NOT NULL,
    company           VARCHAR(500),
    company_id        VARCHAR(128),
    description       TEXT,
    experience        VARCHAR(255),
    employment        VARCHAR(255),
    schedule          VARCHAR(255),
    work_format       VARCHAR(32),
    salary_from       INTEGER,
    salary_to         INTEGER,
    salary_currency   VARCHAR(16),
    salary_gross      BOOLEAN,
    location          VARCHAR(500),
    url               TEXT,
    published_at      TIMESTAMP WITHOUT TIME ZONE,
    source_created_at TIMESTAMP WITHOUT TIME ZONE,
    source_updated_at TIMESTAMP WITHOUT TIME ZONE,
    first_seen_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_seen_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_checked_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    content_hash      VARCHAR(64)                             NOT NULL,
    active            BOOLEAN                                 NOT NULL,
    archived_at       TIMESTAMP WITHOUT TIME ZONE,
    raw_payload       JSONB,
    CONSTRAINT pk_vacancies PRIMARY KEY (id)
);

CREATE TABLE vacancy_requirements
(
    vacancy_id  BIGINT  NOT NULL,
    requirement TEXT,
    list_order  INTEGER NOT NULL,
    CONSTRAINT pk_vacancy_requirements PRIMARY KEY (vacancy_id, list_order)
);

CREATE TABLE vacancy_responsibilities
(
    vacancy_id     BIGINT  NOT NULL,
    responsibility TEXT,
    list_order     INTEGER NOT NULL,
    CONSTRAINT pk_vacancy_responsibilities PRIMARY KEY (vacancy_id, list_order)
);

CREATE TABLE vacancy_skills
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vacancy_id       BIGINT                                  NOT NULL,
    skill            VARCHAR(255)                            NOT NULL,
    normalized_skill VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_vacancy_skills PRIMARY KEY (id)
);

CREATE TABLE vacancy_sync_state
(
    source             VARCHAR(64) NOT NULL,
    last_started_at    TIMESTAMP WITHOUT TIME ZONE,
    last_successful_at TIMESTAMP WITHOUT TIME ZONE,
    last_finished_at   TIMESTAMP WITHOUT TIME ZONE,
    status             VARCHAR(32) NOT NULL,
    last_error         VARCHAR(1000),
    market_version     BIGINT      NOT NULL,
    CONSTRAINT pk_vacancy_sync_state PRIMARY KEY (source)
);

ALTER TABLE vacancies
    ADD CONSTRAINT uk_vacancies_source_external UNIQUE (source, external_id);

ALTER TABLE vacancy_skills
    ADD CONSTRAINT uk_vacancy_skills_vacancy_normalized UNIQUE (vacancy_id, normalized_skill);

ALTER TABLE vacancy_skills
    ADD CONSTRAINT FK_VACANCY_SKILLS_ON_VACANCY FOREIGN KEY (vacancy_id) REFERENCES vacancies (id);

ALTER TABLE analysis_profile_technologies
    ADD CONSTRAINT fk_analysis_profile_technologies_on_analysis_profile_entity FOREIGN KEY (profile_id) REFERENCES analysis_profiles (id);

ALTER TABLE market_snapshot_criteria
    ADD CONSTRAINT fk_market_snapshot_criteria_on_market_snapshot_entity FOREIGN KEY (snapshot_id) REFERENCES market_snapshots (id);

ALTER TABLE market_snapshot_requirements
    ADD CONSTRAINT fk_market_snapshot_requirements_on_market_snapshot_entity FOREIGN KEY (snapshot_id) REFERENCES market_snapshots (id);

ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);

ALTER TABLE vacancy_requirements
    ADD CONSTRAINT fk_vacancy_requirements_on_vacancy_entity FOREIGN KEY (vacancy_id) REFERENCES vacancies (id);

ALTER TABLE vacancy_responsibilities
    ADD CONSTRAINT fk_vacancy_responsibilities_on_vacancy_entity FOREIGN KEY (vacancy_id) REFERENCES vacancies (id);